name: TF Module  workflow
run-name: "TF Module  workflow"
env:
  TF_VERSION: "1.6.5"
  GO_VERSION: '1.21'
on:
  workflow_dispatch:
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main
jobs:
  security_check:
    name: "Security Scan"
    environment: dev
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.5
    - name: Checkov GitHub Action
      uses: bridgecrewio/checkov-action@v12.1347.0
      with:
        directory: .
        soft_fail_on: false
        download_external_modules: true
  test_module:
    name: "Test Module"
    needs: security_check
    environment: dev
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}
    steps:
    - uses: actions/checkout@v4.1.5
    - uses: actions/setup-go@v5.0.1
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Go mod Tidy
      run: go mod tidy

    - uses: hashicorp/setup-terraform@v2
      name: Setup Terraform
      with:
        terraform_version: ${{ env.TF_VERSION}}
        terraform_wrapper: false

    - name: Test Module
      working-directory: test
      run: go test -v
          
  update_document:
    needs: test_module
    if: github.ref == 'refs/heads/main'  && always()
    name: 'Update Documentation'
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.5
    - name: update doc
      uses: terraform-docs/gh-actions@v1.1.0
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "true"
      

