name: TF Module  workflow
run-name: "TF Module  workflow"
env:
  TF_VERSION: "1.6.5"
  GO_VERSION: '1.21'
on:
  workflow_dispatch:
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main
jobs:
  security_check:
    name: "Security Scan"
    environment: dev
    #if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.5
    - name: Checkov GitHub Action
      uses: bridgecrewio/checkov-action@v12.1347.0
      with:
        directory: .
        soft_fail_on: false
        download_external_modules: true

          
      
